### ISSUE TITLE
Problems with Patch operation on group members 

### ISSUE THREAD

**Issue by steverash** [AzureAD/SCIMReferenceCode#10]
Hi,

I've noticed a couple of problems with patch operations on group members.

1.  A patch operation to remove a single member removes all members.    This seems to be due to the code creating a new empty list of the value property of the patch operation has a null value.   

```
                            case OperationName.Remove:
                                if (null == group.Members)
                                {
                                    break;
                                }

                                if (operation?.Value?.FirstOrDefault()?.Value == null)
                                {
                                    group.Members = Enumerable.Empty<Member>();
                                    break;
                                }

```

2.  Adding a member allows the adding of the same user id more than once.

Thanks,

Steve

**Comment by ArvindHarinder1** [comment]
@steverash  thanks for the feedback. Could you provide screenshots of a repro for #1? We're not able to repro it. We're trying to adhere to the standard as described in the screenshot below. We'll be able to address #2.

**Comment by steverash** [comment]
Sure, here are the steps I went through with this sample app in postman

First, create a group with 2 members

```
{
  "schemas": ["urn:ietf:params:scim:schemas:core:2.0:Group"],
  "externalId":"ABCDEFE-B840-47E7-8FBE-543534534543",
  "displayName": "New group",
  "members":
  [
  	{
  		"value":"E367CCBD-B840-47E7-8FBE-B801A18DB3E3",
  		"display":"Test user 1"
  	},
  	{
  		"value":"A367CCBD-B840-47E7-8FBE-B801A18DB3BB",
  		"display":"Test user 2"
  	}	
  ]
}
```

Then remove a single member

```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "remove",
            "path": "members[value eq \"E367CCBD-B840-47E7-8FBE-B801A18DB3E3\"]"
        }
    ]
}
```

3.  Get the group and you will see no members

```
{
    "meta": {
        "resourceType": "Group"
    },
    "displayName": "New group",
    "members": [],
    "externalId": "ABCDEFE-B840-47E7-8FBE-543534534543",
    "id": "e12450c3-2387-4cdd-ae3b-25ee1522acce",
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:Group"
    ]
}
```

**Comment by steverash** [comment]
As an alternative fix, I've put a PR in based on a fix I've done on my fork.  PR is here : #14

**Comment by ArvindHarinder1** [comment]
Closed with this PR. https://github.com/AzureAD/SCIMReferenceCode/pull/25
