### ISSUE TITLE
/schemas and /ResourceTypes endpoints returning empty result

### ISSUE THREAD

**Issue by parmanandkalkal** [AzureAD/SCIMReferenceCode#17]
Hi,

First of all thanks for sharing such a nice and efficient scim server implementation code. Every thing works fine except /schemas and /ResourceTypes  endpoints.

Looks these endpoints are set to return empty collection. Could you please help me these endpoints working ?

 public abstract class ProviderBase : IProvider
    {
       

        private static readonly Lazy<IReadOnlyCollection<TypeScheme>> TypeSchema =
            new Lazy<IReadOnlyCollection<TypeScheme>>(
                () => **Array.Empty<TypeScheme>()**);  // looks this is set as empty

     
        private static readonly Lazy<IReadOnlyCollection<Core2ResourceType>> Types =
            new Lazy<IReadOnlyCollection<Core2ResourceType>>(
                () =>
                    Array.Empty<Core2ResourceType>()); // looks this is set as empty

        public virtual bool AcceptLargeObjects
        {
            get;
            set;
        }

        public virtual IReadOnlyCollection<Core2ResourceType> ResourceTypes
        {
            get
            {
                return ProviderBase.Types.Value;
            }
        }

        public virtual IReadOnlyCollection<TypeScheme> Schema
        {
            get
            {
                return ProviderBase.TypeSchema.Value;
            }
        }
		
		...
}

**Comment by ArvindHarinder1** [comment]
@parmanandkalkal we are looking at addressing this.

**Comment by ArvindHarinder1** [comment]
@parmanandkalkal could you please take a look at this and provide any feedback that you may have? https://github.com/AzureAD/SCIMReferenceCode/pull/30
