### ISSUE TITLE
Possible issue in test: Post emp1 with string "True"

### ISSUE THREAD

**Issue by plamenGo** [AzureAD/SCIMReferenceCode#21]
This test 

Post emp1 with string "True"

Posts the following body

```
{
    "userName": "emp1",
    "active": "True",
}
```

However the RFC defines the **active** field as a boolean. Is "True" expected to work in order to support an Azure AD integration? I am happy to open a pull request to address this.

**Comment by ArvindHarinder1** [comment]
You are correct that active is a boolean in the spec. Unfortunately our service sends it as a string today, hence the test. We are looking to change this in the future, but can't yet without impacting existing integrations.
