### ISSUE TITLE
Possibly invalid test

### ISSUE THREAD

**Issue by plamenGo** [AzureAD/SCIMReferenceCode#22]
The test called 'Post enterprise user' in the Postman collection of tests, specifies this as part of it's body:

```
            "primary": false
        }
    ],
    "Department": "some department",
    "displayName": "Kimberly Baker",
    "emails": [

```

The department attribute is part of the extension schema. Should it be wrapped like in the other Post Enterprise User test:

`    "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
    		"Department": "bob",
    		"Manager" : { "Value": "SuzzyQ" }
    }`

**Comment by ArvindHarinder1** [comment]
You're right department should be in the enterprise user. If you could include the fix in your PR that would be great. Was a mistake in the test.

**Comment by plamenGo** [comment]
ok, added to https://github.com/AzureAD/SCIMReferenceCode/pull/26

**Comment by plamenGo** [comment]
fixed, closing issue
