### ISSUE TITLE
Support for Azure B2C?

### ISSUE THREAD

**Issue by RedBlue1776** [AzureAD/SCIMReferenceCode#29]
I have Azure B2C tenants that I would like to provision in other connected directories.

Can I use B2C as a source?

**Comment by ArvindHarinder1** [comment]
Hi unfortunately provisioning isn't supported for B2C

**Comment by RedBlue1776** [comment]
Any chance you could provide tips or hints on what I may need to supplement or code in a fork that might add this functionality? (e.g. for AAD functionality that isn't yet present in B2C, or just different)

**Comment by ArvindHarinder1** [comment]
@RedBlue1776  to clarify the Azure AD SCIM client doesn't support B2C tenants. It's work Azure AD needs to do. You wouldn't need to develop a SCIM server differently for B2C. I would recommend posting here to add support for it  https://feedback.azure.com/forums/169401-azure-active-directory?category_id=160596

**Comment by craigeaw** [comment]
> Hi unfortunately provisioning isn't supported for B2C

Could you expand on this? What exactly does this mean? I am able to provision using an enterprise app in Azure B2C. Is provisioning now supported?

**Comment by dalbani** [comment]
@craigeaw can you elaborate on which "enterprise app" you used? Does this app uses SCIM then??

**Comment by craigeaw** [comment]
> @craigeaw can you elaborate on which "enterprise app" you used? Does this app use SCIM then??

I used a ServiceNow enterprise app in B2C. We were able to provision users to ServiceNow with no issues. We followed this documentation: https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/servicenow-provisioning-tutorial

**Comment by craigeaw** [comment]
@dalbani We just found out that on-demand provisioing is possible. However, the provisioning service is not supported. As soon as you turn on and enable provisioning you get this error:

Provisioning has been quarantined. See quarantine details for more information.
Quarantine details:
User provisioning is not supported for your tenant, which is most likely an Azure Active Directory "B2C" tenant.

Thanks Microsoft. Could you please disable provisioning entirely if it's not supported so we don't waste time setting it up?

**Comment by aecvargas** [comment]
@craigeaw Did you manage to figure out how you could provision users? I'm currently researching this and have been looking at B2B and B2C. I'm looking into how SAML SSO and SCIM provisioning can be integrated into a public-facing web portal that we develop and host. We currently hold the users on our database but the clients would like to be able to manage and have these users on their active directory. So it seems like this use case is more fitted to a B2C tenant but what I'm trying to achieve doesn't seem to be supported with B2C

**Comment by craigeaw** [comment]
> @craigeaw Did you manage to figure out how you could provision users? I'm currently researching this and have been looking at B2B and B2C. I'm looking into how SAML SSO and SCIM provisioning can be integrated into a public-facing web portal that we develop and host. We currently hold the users on our database but the clients would like to be able to manage and have these users on their active directory. So it seems like this use case is more fitted to a B2C tenant but what I'm trying to achieve doesn't seem to be supported with B2C

The provisioning service is not supported for B2C. I could only provision manually using SCIM in B2C (one at a time). This was not a viable option so we set up JIT provisioning with the app.
