### ISSUE TITLE
Question: is the SCIM project available as a nuget package?

### ISSUE THREAD

**Issue by danludwig** [AzureAD/SCIMReferenceCode#31]
When searching nuget, I found a package named Microsoft.SystemForCrossDomainIdentityManagement, but it seems older than this project. Is it possible to consume the SCIM assembly from a sample web hosting project from a well-known nuget package, instead of using the source?

**Comment by ArvindHarinder1** [comment]
@danludwig we don't support the nuget package today. We've transitioned to the open source model.
