### ISSUE TITLE
Add ASPNETCORE_ENVIRONMENT with the value of Development.

### ISSUE THREAD

**Issue by kenwith** [AzureAD/SCIMReferenceCode#39]
I don't seem to be able to submit a PR to the wiki. The PR would be to add the following to Step 7 of deploy page.

Also add ***ASPNETCORE_ENVIRONMENT*** with the value of "Development". Note that you will need to get a token using the /scim/token endpoint for testing as described on the testing page.

**Comment by ArvindHarinder1** [comment]
Updated the wiki.
